# Variables
adjective_1 = input("Can I get an adjective")
noun_1 = input("Can I get an noun")
adjective_2 = input("Can I get an adjective")
verb_1 = input("Can I get an verb")
noun_2 = input("Can I get an noun")
verb_2 = input("Can I get a verb")
adjective_3 = input("Can I get adjective")
noun_3 = input("Can I get a noun")
verb_3 = input("Can I get a verb")
adjective_4 = input("Can I get an adjective")
print("There was once a %s grasshopper, he lived in a %s" % (adjective_1, noun_1))
print("The grasshopper was %s , he then %s to the store" % (adjective_2, verb_1))
print("At the %s, he %s for groceries" % (noun_2, verb_2))
print("He got an %s fruit, and went back to his %s" % (adjective_3, noun_3))
print(" At home he %s the food, and sat on his %s couch" % (verb_3, adjective_4))